#!/bin/bash

# SPDX-FileCopyrightText: Copyright 2025 free-pmx
# SPDX-License-Identifier: AGPL-3.0-only

declare -i status=0

source "/usr/lib/free-pmx/no-subscription-util" \
    && init_out \
    || exit 255

[[ -n $1 ]] && declare -r aptsrcdef=$1 || exit 1

[[ -n $FREE_PMX_APTEXT ]] && [[ -n $FREE_PMX_DEBIAN ]] || exit 2

declare -ra asd_vars=(DISABLE CREATE FROM URI SUITE COMPONENT KEY)
declare -A asd
source_kv "$aptsrcdef" asd "${asd_vars[@]}" \
    && check_kv_allset asd "${asd_vars[@]}" \
    || {
        print ERR "! Corrupt source definition: $aptsrcdef"
        exit $((status |= 1))
    }

if [[ ! -f ${asd[DISABLE]} ]]; then
    print OUT "~ Original not present: ${asd[DISABLE]}"
elif mv "${asd[DISABLE]}"{,.disabled}; then
    print OUT "+ Disabled original: ${asd[DISABLE]}"
else
    print ERR "! Could not disable original: ${asd[DISABLE]}"
    ((status |= 1))
fi

declare policy
if ! policy=$(apt_policy_match "${asd[URI]}" "${asd[SUITE]}" "${asd[COMPONENT]}"); then
    print ERR "! Unable to check APT policy for duplicates."
    ((status |= 1))
elif [[ -n $policy ]]; then
    print OUT "~ New NOT created as same record already exists as per APT policy:"
    print OUT "  $policy"
elif subst_props asd URI SUITE COMPONENT KEY \
    < "${aptsrcdef%/*}/${asd[FROM]}" \
    > "${asd[CREATE]}"; then

    print OUT "+ Created new: ${asd[CREATE]}"
else
    print ERR "! Could not create: ${asd[CREATE]}"
    ((status |= 1))
fi

exit $((status))
