#!/bin/bash

# SPDX-License-Identifier: AGPL-3.0-only

source "/usr/lib/free-pmx/no-subscription-util" 2> /dev/null \
|| { echo "Internal error, aborting." >&2; exit 1; }

declare -i status=0

[[ -n $1 ]] && declare -r repo_key=$1 || exit 1
[[ -n $2 ]] && declare -r repo_key_url=$2 || exit 1

if [[ -f $repo_key ]]; then
    echo "+ Already present:"
else 
    echo "~ Not present, retrieving: $repo_key_url ..."
    if wget -q "$repo_key_url" -O "$repo_key" 2> /dev/null; then
        echo "Retrieved:"
    else
        echo "! Errors attempting to retrieve or store key." >&2
        status=1
    fi
fi

export GNUPGHOME=$(mktemp -d /tmp/gnupg-XXXXXX) 2> /dev/null
[[ -d "$GNUPGHOME" ]] || unset GNUPGHOME

gpg --show-keys "$repo_key" 2> /dev/null \
|| { echo "! Errors examining key details." >&2; status=1; }

[[ -d "$GNUPGHOME" ]] && rm -rf "$GNUPGHOME" 2> /dev/null

declare checksum
if checksum=$(checksum "$repo_key" 512); then
    echo "sha512 $checksum"
else
    echo "! Errors calculating key checksum." >&2
    status=1
fi

exit $status
