#!/bin/bash

source "${BASH_SOURCE[0]%/*}"/util && init || exit 255

out_dir=$(pwd -P)
repo_dir=${GIT_WORK_TREE:-$out_dir}

found_buildmeta=("$repo_dir"/*.buildmeta)
((${#found_buildmeta[@]} == 1))
buildmeta=${found_buildmeta[0]}
[[ -f $buildmeta ]]
buildmeta_fname=${buildmeta##*/}

target="${buildmeta_fname%%.buildmeta}"
package=${target%%_*}
version=${target#*_}

(cd "$repo_dir" && source .permsrc || exit 1)

source "$buildmeta"
export SOURCE_DATE_EPOCH DPKG_DEB_COMPRESSOR_TYPE

tmp_deb=$(mktemp "$package"_XXXXXX.deb)
dpkg-deb --build --root-owner-group "$repo_dir/$package" "$tmp_deb"

read -r deb_package deb_version <<< "$(
    dpkg-deb --show --showformat='${Package} ${Version}\n' \
        "$tmp_deb"
)"

[[ $package == "$deb_package" ]]
[[ $version == "$deb_version" ]]

deb_fname="${deb_package}_${deb_version}.deb"
mv -v "$tmp_deb" "$out_dir/$deb_fname"

deb_info_fname="$deb_fname".info

sha256sum --check <<< "$DEB_SHA256  $out_dir/$deb_fname"

cat >&3 << EOF
DEB=$out_dir/$deb_fname
DEB_INFO=$out_dir/$deb_info_fname

EOF

cat >> "$out_dir/$deb_info_fname" << EOF
GIT_URL=$GIT_URL
GIT_COMMIT=$GIT_COMMIT
GIT_REF=$GIT_REF

EOF

tee "$out_dir/$deb_info_fname" >&3 << EOF
DEB_PACKAGE=$deb_package
DEB_VERSION=$deb_version

DEB_SHA256=$DEB_SHA256
DEB_URL=$DEB_URL

EOF

cat >&3 << EOF
CHECK_BUILD=pass
EOF
