#!/bin/bash

source "${BASH_SOURCE[0]%/*}"/util && init || exit 255

req_apt wget

tmp_deb=$(mktemp "/tmp/$DEB_PACKAGE"_XXXXXX.deb)
wget --no-verbose -O "$tmp_deb" "$DEB_URL"
sha256sum --check <<< "$DEB_SHA256  $tmp_deb"

cat >&3 << EOF
CHECK_URL_LAST=$(date --rfc-3339=seconds --utc)

CHECK_URL=pass
EOF
