#!/bin/bash

init() {
    exec 3>&1 1>&2 || exit 255
    trap 'echo "${BASH_SOURCE[0]##*/}: Error $? (l.$LINENO) - aborted."; exit 1;' ERR
}

req_apt() {
    (($# > 0)) || return 255

    declare -x DEBIAN_FRONTEND=noninteractive
    apt-get -qq update
    apt-get -qqo Dpkg::Use-Pty=0 satisfy "$@"
}
