#!/bin/bash
set -e

source "/usr/lib/free-pmx/no-subscription-common" \
    && declare_ns_globals \
    && declare_nn_globals \
    || {
        echo "ERROR: ${0##*/} - auto-run skipped." >&2
        exit 0
    }

case "$1" in

configure)

    no-subscription -a || echo "ISSUES reported: $1" >&2
    no-nag -a || echo "ISSUES reported: $1" >&2
    ;;

triggered)

    for t in $2; do

        if [[ -v APTSRC_TARGET_TO_ID[$t] ]]; then
            no-subscription -at "$t" || echo "ISSUES reported: $1 $t" >&2
        elif [[ -v PATCHDEF_TARGET_TO_IDS[$t] ]]; then
            no-nag -at "$t" || echo "ISSUES reported: $1 $t" >&2
        fi

    done
    ;;

abort-upgrade | abort-remove | abort-deconfigure)

    :
    ;;

*)

    echo "ERROR: ${0##*/} - unknown argument: $1" >&2
    exit 1
    ;;

esac
