on:
  workflow_dispatch:
  push:
    branch:
      - main
    paths:
      - '*.buildmeta'

env:
  GIT_URL: "${{ github.repositoryUrl }}"
  GIT_COMMIT: "${{ github.sha }}"
  GIT_REF: "${{ github.ref }}"

defaults:
  run:
    shell: bash
    working-directory: repo
jobs:
  reproducible-build-check:
    name: "Reproducible Build"
    runs-on: ubuntu-latest
    container: debian:12
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        path: repo
    - name: Check if build can be reproduced
      run: .github/repro-build/check-build >> $GITHUB_ENV
    - name: Check if published package checksum matches
      run: .github/repro-build/check-url >> $GITHUB_ENV
    - name: Report
      if: always()
      run: .github/repro-build/report >> $GITHUB_STEP_SUMMARY
    - name: Create working directory bundle artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        path: repo
        include-hidden-files: true
        retention-days: 1
